# Generated by Django 3.1.3 on 2021-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_nombre', models.CharField(max_length=100)),
                ('usuario_password', models.CharField(max_length=100)),
                ('empresa_nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
