# Generated by Django 3.1.3 on 2021-06-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API_Loguin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Niveles_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nivel_usuario', models.CharField(max_length=100)),
                ('descripcion_nivel_usuario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso_Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_permiso', models.CharField(max_length=100)),
                ('descripcion_permiso', models.CharField(max_length=200)),
                ('nombre_modulo', models.CharField(max_length=200)),
                ('ruta_modulo', models.CharField(max_length=200)),
                ('listar', models.BooleanField(default=False)),
                ('ver', models.BooleanField(default=False)),
                ('crear', models.BooleanField(default=False)),
                ('modificar', models.BooleanField(default=False)),
                ('eliminar', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='empresa_nombre',
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('direccion_sucursal', models.CharField(max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Loguin.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Loguin.permiso_usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Loguin.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Acceso_Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_acceso', models.DateTimeField(auto_now_add=True)),
                ('mensaje_acceso', models.CharField(max_length=250)),
                ('Niveles_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Loguin.niveles_usuario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Loguin.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Loguin.usuario')),
            ],
        ),
    ]
