# Generated by Django 3.1.3 on 2021-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
    ]
